"""Starlette application factory for local Hermes A2A endpoints and sidecars."""

from __future__ import annotations

from functools import partial
from pathlib import Path
from typing import Iterable

from a2a.server.routes.agent_card_routes import create_agent_card_routes
from a2a.server.routes.jsonrpc_routes import create_jsonrpc_routes
from a2a.server.routes.rest_routes import create_rest_routes
from a2a.server.tasks import InMemoryPushNotificationConfigStore, InMemoryTaskStore
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.types import ASGIApp, Receive, Scope, Send

from hermes_a2a.agent_card import build_agent_card
from hermes_a2a.executor import SafeEchoExecutor
from hermes_a2a.handler import SafeRequestHandler, authenticated_extended_card


class TestEphemeralPeerAuthMiddleware:
    """M17b-only peer authorization gate for synthetic sidecar tests.

    The token is generated by the pilot process and never persisted to the roster,
    Agent Card, receipt, or artifact manifest. Public Agent Card discovery remains
    unauthenticated; protocol routes require both an allowed peer id and token.
    """

    def __init__(self, app: ASGIApp, *, allowed_peer_ids: Iterable[str], test_token: str | None) -> None:
        self.app = app
        self.allowed_peer_ids = frozenset(allowed_peer_ids)
        self.test_token = test_token

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http" or self.test_token is None:
            await self.app(scope, receive, send)
            return
        if scope.get("path") == "/.well-known/agent-card.json":
            await self.app(scope, receive, send)
            return
        headers = {key.decode("latin1").lower(): value.decode("latin1") for key, value in scope.get("headers", [])}
        supplied_token = headers.get("x-hermes-a2a-test-token")
        supplied_peer = headers.get("x-hermes-a2a-peer-id")
        if supplied_token != self.test_token or supplied_peer not in self.allowed_peer_ids:
            response = JSONResponse({"error": "A2A peer authorization denied"}, status_code=403)
            await response(scope, receive, send)
            return
        await self.app(scope, receive, send)


def build_handler(
    *,
    receipt_dir: Path,
    require_auth: bool = False,
    api_key: str | None = None,
    agent_name: str = "Hermes A2A Local",
    agent_description: str = "Local-only canonical A2A v1.0.0 endpoint backed by Hermes safety gates.",
    base_url: str = "http://127.0.0.1",
    grpc_url: str = "127.0.0.1:0",
) -> SafeRequestHandler:
    card = build_agent_card(
        base_url=base_url,
        grpc_url=grpc_url,
        name=agent_name,
        description=agent_description,
        require_auth=require_auth,
    )
    extended_card = build_agent_card(
        base_url=base_url,
        grpc_url=grpc_url,
        name=agent_name,
        description=agent_description,
        require_auth=require_auth,
    )
    executor = SafeEchoExecutor(Path(receipt_dir))
    return SafeRequestHandler(
        agent_executor=executor,
        task_store=InMemoryTaskStore(),
        agent_card=card,
        push_config_store=InMemoryPushNotificationConfigStore(),
        extended_agent_card=extended_card,
        extended_card_modifier=partial(authenticated_extended_card, api_key=api_key if require_auth else None),
    )


def build_app(
    *,
    receipt_dir: Path,
    require_auth: bool = False,
    api_key: str | None = None,
    agent_name: str = "Hermes A2A Local",
    agent_description: str = "Local-only canonical A2A v1.0.0 endpoint backed by Hermes safety gates.",
    base_url: str = "http://127.0.0.1",
    grpc_url: str = "127.0.0.1:0",
    allowed_peer_ids: Iterable[str] = (),
    test_token: str | None = None,
) -> Starlette:
    handler = build_handler(
        receipt_dir=receipt_dir,
        require_auth=require_auth,
        api_key=api_key,
        agent_name=agent_name,
        agent_description=agent_description,
        base_url=base_url,
        grpc_url=grpc_url,
    )
    card = build_agent_card(
        base_url=base_url,
        grpc_url=grpc_url,
        name=agent_name,
        description=agent_description,
        require_auth=require_auth,
    )
    routes = []
    routes.extend(create_agent_card_routes(card))
    routes.extend(create_jsonrpc_routes(handler, rpc_url="/"))
    routes.extend(create_rest_routes(handler))
    app = Starlette(debug=False, routes=routes)
    app.add_middleware(TestEphemeralPeerAuthMiddleware, allowed_peer_ids=allowed_peer_ids, test_token=test_token)
    return app
